plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-ccs-computing.github.io
baseurl: "/S25-20A"

course: "CMPTGCS 20A"
qtr: "S25"
instructor: "Richert Wang"
quarter: "Spring 2025"
piazza_url: 
gauchospace_course_page:
gradescope_class_url:

github_url: https://github.com/ucsb-ccs-computing/S25-20A

start_week: 1
start_date: 2025-03-30 00:00:00.00-7:00
num_weeks: 10
extra_exam_week: true

cal_dates: >                                                                    
  [                                                                            
    {"label":"S25 1st day of instruction", "date":"2025-03-31" },
    {"label":"Memorial Day", "date":"2025-05-26" },
    {"label":"S24 instruction ends", "date":"2025-06-06" },
    {"label":"S24 qtr ends", "date":"2025-06-13" }                              
  ]

kramdown:
   parse_block_html: true
   default_lang: cpp

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        
include:
   - _pages
   
timezone: America/Los_Angeles

collections:
  info:
    output: true
    permalink: /info/:path/
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
